apiVersion: syndesis.io/v1beta2
kind: Syndesis
metadata:
  name: app
spec:
  components:
    database:
      resources:
        limit:
          memory: "255Mi"
        request:
          memory: "255Mi"
        volumeCapacity: 5Gi
    server:
      features:
        integrationLimit: 5
        testSupport: true
